config/routes.rb
R20130214Cookbook::Application.routes.draw do

resources :books, :recipes, :ingredients

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  cuisine    :string(255)
#  chef       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
attr_accessible :title, :cuisine, :chef, :image
has_many :recipes

end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :decimal(, )
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
attr_accessible :name, :measurement, :cost, :image
has_and_belongs_to_many :recipes
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :integer
#  servingsize  :integer
#  instructions :text
#  image        :text
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
attr_accessible :name, :course, :cooktime, :servingsize, :image, :book_id
belongs_to :book
has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.create(params[:book])
    redirect_to(book)
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update_attributes(params[:book])
    redirect_to(book)
  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to(books_path)

  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController


  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    ingredient = Ingredient.create(params[:ingredient])
    redirect_to(ingredient)
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    ingredient = Ingredient.find(params[:id])
    ingredient.update_attributes(params[:ingredient])
    redirect_to(ingredient)
  end

  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.delete
    redirect_to(ingredients_path)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController



  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe = Recipe.create(params[:recipe])
    redirect_to(recipe)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe.update_attributes(params[:recipe])
    redirect_to(recipe)
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipes_path)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

  <br>
<%= f.text_field :title, :placeholder => "Title" %>
<%= f.label :title,:autofocus => 'autofocus' %>
<br>
<%= f.text_field :cuisine, :placeholder => "Cuisine" %>
<%= f.label :cuisine %>
<br>
<%= f.text_field :chef, :placeholder => "Chef" %>
<%= f.label :chef %>
<br>
<%= f.text_field :image, :placeholder => "Image" %>
<%= f.label :image %>
<br>
<% Recipe.order(:name).each do |recipe| %>
  <span><%= recipe.name %></span>
  <%= check_box_tag 'book[recipe_ids][]', recipe.id, recipe.in?(@book.recipes.to_a) %>
  <% end %>


<%= f.submit %>

<% end %>

app/views/books/edit.html.erb
<%= render :partial => 'form' %>

app/views/books/index.html.erb
    <ul>
      <li><%= link_to('Add a New Book', new_book_path) %></li>
    </ul>
</nav>
<p>
<ol>
<% @books.each do |book| %>
<li>
  <ul>
    <li><%= link_to(book.title, book) %> </li>
    <li><%= book.cuisine %> </li>
    <li><%= book.chef %> </li>
    </li><%= link_to 'Delete', book, :method => :delete %>
  <%= link_to 'Edit', edit_book_path(book) %>
  </li>
    <li><%= image_tag book.image, :class =>'bookimg' %> </li>
  </ul>
</li>
</p>
<% end %>

</ol>

app/views/books/new.html.erb
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<p>
  <br>
<%= link_to(@book.title, @book) %>
<br>
<%= @book.cuisine %>
<br>
<%= @book.chef %>
<br>
<%= image_tag(@book.image) %>


<% @book.recipes.each do |recipe| %>
  <% recipe.name %>
  <% image_tag(recipe.image) %>

  <br>

  <% recipe.ingredients.each do |ingredient| %>
    <%= ingredient.name %>
    <%= image_tag ingredient.image, :height => '350px', :width => '350px' %>
  </p>
    <% end %>

  <% end %>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>

  <br>
<%= f.text_field :name, :placeholder => "Name" %>
<%= f.label :name,:autofocus => 'autofocus' %>
<br>
<%= f.text_field :measurement, :placeholder => "Measurement" %>
<%= f.label :measurement %>
<br>
<%= f.text_field :cost, :placeholder => "Cost" %>
<%= f.label :cost %>
<br>
<%= f.text_field :image, :placeholder => "Image" %>
<%= f.label :image %>
<br>
<%= f.submit %>

<% end %>

app/views/ingredients/edit.html.erb
<%= render :partial => 'form' %>

app/views/ingredients/index.html.erb
<ul>
      <li><%= link_to('Add New Ingredient', new_ingredient_path) %></li>
    </ul>
</nav>
<p>

<ol>
<% @ingredients.each do |ingredient| %>
<li>
  <ul>
    <li><%= link_to(ingredient.name, ingredient) %> </li>

    <li><%= ingredient.measurement %> </li>
    <li><%= ingredient.cost %> </li>
     </li><%= link_to 'Delete', ingredient, :method => :delete %>
  <%= link_to 'Edit', edit_ingredient_path(ingredient) %>
  </li>
    <li><%= image_tag(ingredient.image, :class =>'ingredientimg') %> </li>
  </ul>
</li>
</p>
<% end %>

</ol>

app/views/ingredients/new.html.erb
<%= render :partial => 'form' %>

app/views/ingredients/show.html.erb
<p>
<br>
<%= link_to(@ingredient.name, @ingredient) %>
<br>
<%= @ingredient.measurement %>
<br>
<%= @ingredient.cost %>
<br>
<%= image_tag(@ingredient.image) %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R20130214Cookbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class='container'>
    <nav>
      <ul>
        <li><%= link_to('Ingredients', ingredients_path) %></li>
        <li><%= link_to('Books', books_path) %></li>
        <li><%= link_to('Recipes', recipes_path) %></li>
      </ul>
    </nav>
<%= yield %>
  </div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>

  <br>
<%= f.text_field :name, :placeholder => "Name" %>
<%= f.label :name,:autofocus => 'autofocus' %>
<br>
<%= f.text_field :course, :placeholder => "Course" %>
<%= f.label :course %>
<br>
<%= f.text_field :cooktime, :placeholder => "Cooktime" %>
<%= f.label :cooktime %>
<br>
<%= f.text_field :servingsize, :placeholder => "Servingsize" %>
<%= f.label :servingsize %>
<br>
<%= f.text_field :image, :placeholder => "Image" %>
<%= f.label :image %>
<br>
<%= f.submit %>

<% end %>

app/views/recipes/edit.html.erb
<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<ul>
      <li><%= link_to('Add New Recipe', new_recipe_path) %></li>
    </ul>
</nav>
<p>
<ol>
<% @recipes.each do |recipe| %>
<li>
  <ul>
    <li><%= link_to(recipe.name, recipe) %> </li>
    <li><%= recipe.course %> </li>
    <li><%= recipe.cooktime %> </li>
    <li><%= recipe.servingsize %> </li>
  </li><%= link_to 'Delete', recipe, :method => :delete %>
  <%= link_to 'Edit', edit_recipe_path(recipe) %>
  </li>
    <li><%= image_tag(recipe.image, :class =>'recipeimg') %> </li>
  </ul>
</li>
</p>
<% end %>

</ol>

app/views/recipes/new.html.erb
<%= form_for @recipe do |f| %>

  <br>
<%= f.text_field :name, :placeholder => "Name" %>
<%= f.label :name,:autofocus => 'autofocus' %>
<br>
<%= f.text_field :course, :placeholder => "Course" %>
<%= f.label :course %>
<br>
<%= f.text_field :cooktime, :placeholder => "Cooktime" %>
<%= f.label :cooktime %>
<br>
<%= f.text_field :servingsize, :placeholder => "Servingsize" %>
<%= f.label :servingsize %>
<br>
<%= f.text_field :image, :placeholder => "Image" %>
<%= f.label :image %>
<br>
<%= f.submit %>

<% end %>

app/views/recipes/show.html.erb
<p>
<br>
<%= link_to(@recipe.name, @recipe) %>
<br>
<%= @recipe.course %>
<br>
<%= @recipe.cooktime %>
<br>
<%= @recipe.servingsize %>
<%= image_tag(@recipe.image) %>
<br>




  <br>